name: Publish JBManagerBot to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/manage/project/jb-manager-bot/ 
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Remove any existing build
      working-directory: ./jb-manager-bot
      run: rm -rf dist
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: latest  
    - name: Build
      working-directory: ./jb-manager-bot
      run: poetry build
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: poetry publish -r testpypi --username $TWINE_USERNAME --password $TWINE_PASSWORD
