# This workflow will upload jb-manager-bot package when a release is created

name: Publish JBManagerBot to Pypi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jb-manager-bot 
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Remove any existing build
      working-directory: ./jb-manager-bot
      run: rm -rf dist
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        version: latest  
    - name: Build
      working-directory: ./jb-manager-bot
      run: poetry build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages_dir: ./jb-manager-bot/dist